(define (problem blocks-5)
 (:domain blocks)
 (:objects A B C D E - block)
 (:init (ontable A) (ontable B) (ontable E)
        (on C A)
        (on D B)
        (clear C)
        (clear D)
        (clear E)
        (handempty))
 (:goal (and (on A B) (on B C) (on C D) (on D E)))
)
